version: "3.0"
services:
  influxdb-query:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    environment:
      MODULE_NAME: "InfluxDB Query"
      MODULE_TYPE: "Processing"
      EGRESS_URLS: "https://testdockercompose.free.beeceptor.com"
      INGRESS_HOST: "0.0.0.0"
      INGRESS_PORT: "80"
      INFLUXDB_URL: ''
      INFLUXDB_API_KEY: ''
      INFLUXDB_ORG: ''
      INFLUXDB_BUCKET: ''
      RUN_AS_STANDALONE: 'yes'
    ports:
      - 80:80